# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lable-service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13lable-service.proto\" \n\x10LableTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"-\n\rLableResponse\x12\r\n\x05label\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x32\x42\n\x0cLableService\x12\x32\n\tSendLable\x12\x11.LableTextRequest\x1a\x0e.LableResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lable_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LABLETEXTREQUEST']._serialized_start=23
  _globals['_LABLETEXTREQUEST']._serialized_end=55
  _globals['_LABLERESPONSE']._serialized_start=57
  _globals['_LABLERESPONSE']._serialized_end=102
  _globals['_LABLESERVICE']._serialized_start=104
  _globals['_LABLESERVICE']._serialized_end=170
# @@protoc_insertion_point(module_scope)
